import { Response } from 'express';
import { cbError } from '@utils';
import { ERRORS } from '@constant';
import { HTTPSTATUS } from '@enum';

const errorHttpStatusMap: Record<string, HTTPSTATUS> = {
  [ERRORS.BAD_REQUEST.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.UNAUTHORIZED.key]: HTTPSTATUS.UNAUTHORIZED,
  [ERRORS.FORBIDDEN.key]: HTTPSTATUS.FORBIDDEN,
  [ERRORS.NOT_FOUND.key]: HTTPSTATUS.NOT_FOUND,
  [ERRORS.CONFLICT.key]: HTTPSTATUS.CONFLICT,
  [ERRORS.INVALID_TOKEN.key]: HTTPSTATUS.UNAUTHORIZED,
  [ERRORS.API_NOT_FOUND.key]: HTTPSTATUS.NOT_FOUND,
  [ERRORS.PARAMETER_MISSING.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.INVALID_PARAMETERS.key]: HTTPSTATUS.UNPROCESSABLE_ENTITY,
  [ERRORS.INVALID_ID.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.CREATE_FAILED.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.UPDATE_FAILED.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.DELETE_FAILED.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.ALREADY_EXISTS.key]: HTTPSTATUS.CONFLICT,
  [ERRORS.USER_NOT_FOUND.key]: HTTPSTATUS.NOT_FOUND,
  [ERRORS.LOGIN_FAIL.key]: HTTPSTATUS.FORBIDDEN,
  [ERRORS.INCORRECT_CREDENTIALS.key]: HTTPSTATUS.UNAUTHORIZED,
  [ERRORS.INVALID_USER_KEY.key]: HTTPSTATUS.UNAUTHORIZED,
  [ERRORS.INVALID_REFRESH_TOKEN.key]: HTTPSTATUS.UNAUTHORIZED,
  [ERRORS.INVALID_OTP.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.EXPIRED_OTP.key]: HTTPSTATUS.BAD_REQUEST,
  [ERRORS.ALREADY_VERIFIED.key]: HTTPSTATUS.CONFLICT,
};

export const handleKnownErrors = (res: Response, error: any): void => {
  const status = error?.key && errorHttpStatusMap[error.key];

  if (status) {
    cbError(res, status, ERRORS[error.key as keyof typeof ERRORS], error);
  } else {
    cbError(res, HTTPSTATUS.INTERNAL_SERVER_ERROR, ERRORS.INTERNAL_SERVER_ERROR, error);
  }
};
